name: Testim E2E
on: [pull_request]

jobs:
    run-testimio-cli:
        runs-on: windows
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '16.13.0'
            - run: npm install -g @testim/testim-cli
            - run : testim --token "Y0jy30lxHFKryRD7ahLKcxRSBVTWOU6WOPfdpNW9Ud5NpYkGoG" --project "f0EhXJOmKz1KgSVNrsdK" --grid "Testim-Grid"
